name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  firebase_storage: ^10.2.18
  flutter_staggered_grid_view: ^0.6.1
  provider: ^6.0.3
  path_provider: ^2.0.11
  image: ^3.2.0
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png



